<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.*" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.41" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeBanking.Core\HomeBanking.Core.csproj" />
    <ProjectReference Include="..\HomeBanking.Infrastructure\HomeBanking.Infrastructure.csproj" />
    <ProjectReference Include="..\HomeBanking.Contracts\HomeBanking.Contracts.csproj" />
  </ItemGroup>

</Project>
